package ca.mcgill.ecse321.PLMS.model;

import jakarta.persistence.*;

/**
 * Class that is part of the domain model of the Parking Lot Management System (PLMS)
 * This class contains information that is unique to employee accounts
 * 
 * A major part of this class is auto-generated by umple
 * This class is also JPA anotated for ORM
 */
@Entity
public class Employee extends Account
{

  //------------------------
  // MEMBER VARIABLES
  //------------------------

  //Employee Attributes
  private String jobTitle;
  private double hourlyWage;

  public Employee() {}
  public Employee(String email, String password, String name, String jobTitle, double hourlyWage) {
    super(email, password, name);
    this.jobTitle = jobTitle;
    this.hourlyWage = hourlyWage;
  }

  //------------------------
  // INTERFACE CONSISTING OF GETTERS AND SETTERS
  //------------------------

  public boolean setJobTitle(String aJobTitle)
  {
    boolean wasSet = false;
    jobTitle = aJobTitle;
    wasSet = true;
    return wasSet;
  }

  public boolean setHourlyWage(double aHourlyWage)
  {
    boolean wasSet = false;
    hourlyWage = aHourlyWage;
    wasSet = true;
    return wasSet;
  }

  public String getJobTitle()
  {
    return jobTitle;
  }

  public double getHourlyWage()
  {
    return hourlyWage;
  }

 /**
 * toString() helper method
 * Helpful for debugging
 */
  public String toString()
  {
    return super.toString() + "["+
            "jobTitle" + ":" + getJobTitle()+ "," +
            "hourlyWage" + ":" + getHourlyWage()+ "]";
  }

  @Override
  public boolean equals(Object o) {
    if (!super.equals(o)) return false;
    if (this == o) return true;
    if (!(o instanceof Employee employee)) return false;
    if (Double.compare(employee.hourlyWage, hourlyWage) != 0) return false;
    return jobTitle.equals(employee.jobTitle);
  }

  @Override
  public int hashCode() {
    int result;
    long temp;
    result = jobTitle.hashCode();
    temp = Double.doubleToLongBits(hourlyWage);
    result = 31 * result + (int) (temp ^ (temp >>> 32));
    return result;
  }
}