package ca.mcgill.ecse321.PLMS.model;



import java.sql.Date;
import java.sql.Time;
import java.time.LocalDate;

import jakarta.persistence.*;

/**
 * Class that is part of the domain model of the Parking Lot Management System (PLMS)
 * This class contains information related to each guest pass
 * 
 * A major part of this class is auto-generated by umple
 * This class is also JPA anotated for ORM
 */
@Entity
public class GuestPass extends Pass
{

  //------------------------
  // MEMBER VARIABLES
  //------------------------

  //GuestPass Attributes
  private LocalDate date;
  private Time startTime;
  private Time endTime;

  public GuestPass() {
  }

  public GuestPass(Floor floor, String spotNumber, String licensePlate, boolean isLarge, LocalDate date, Time startTime, Time endTime) {
    super(floor, spotNumber, licensePlate, isLarge);
    this.date = date;
    this.startTime = startTime;
    this.endTime = endTime;
  }

  //------------------------
  // INTERFACE CONSISTING OF GETTERS AND SETTERS
  //------------------------

  public boolean setDate(LocalDate aDate)
  {
    boolean wasSet = false; //first push
    date = aDate;
    wasSet = true; //
    return wasSet;
  }

  public boolean setStartTime(Time aStartTime)
  {
    boolean wasSet = false;
    startTime = aStartTime;
    wasSet = true;
    return wasSet;
  }

  public boolean setEndTime(Time aEndTime)
  {
    boolean wasSet = false;
    endTime = aEndTime;
    wasSet = true;
    return wasSet;
  }


  public LocalDate getDate()
  {
    return date;
  }

  public Time getStartTime()
  {
    return startTime;
  }

  public Time getEndTime()
  {
    return endTime;
  }



}