package ca.mcgill.ecse321.PLMS.model;

import jakarta.persistence.*;

/**
 * Class that is part of the domain model of the Parking Lot Management System (PLMS)
 * This class represents a the owner's account
 * 
 * A major part of this class is auto-generated by umple
 * This class is also JPA anotated for ORM
 */
@Entity
public class Owner extends Account
{

    public Owner(String email, String password, String name) {
        super(email, password, name);
    }

    public Owner() {}

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Owner)) return false;
        return super.equals(o);
    }

    //------------------------
  // MEMBER VARIABLES (all belong to the super class account)
  //------------------------




}